export { ReactComponent as AlgorandIcon } from './algorand.svg'
export { ReactComponent as NoNotificationIcon } from './no_notification.svg'
export { ReactComponent as AddIcon } from './add.svg'
export { ReactComponent as ArrowDownIcon } from './arrow-down.svg'
export { ReactComponent as GallaryAddIcon } from './gallery-add.svg'
export { ReactComponent as CheckIcon } from './check.svg'
export { ReactComponent as CloseCircleIcon } from './close-circle.svg'
export { ReactComponent as CopyIcon } from './copy.svg'
export { ReactComponent as FilterIcon } from './filter.svg'
export { ReactComponent as LinkIcon } from './link.svg'
export { ReactComponent as LoginIcon } from './login.svg'
export { ReactComponent as MessgeQuestionIcon } from './message-question.svg'
export { ReactComponent as MoonIcon } from './moon.svg'
export { ReactComponent as Notification1Icon } from './notification-1.svg'
export { ReactComponent as NotificationIcon } from './notification.svg'
export { ReactComponent as SearchNormalIcon } from './search-normal.svg'
export { ReactComponent as Send2Icon } from './send-2-1.svg'
export { ReactComponent as SendIcon } from './send-2.svg'
export { ReactComponent as SettingIcon } from './setting-2.svg'
export { ReactComponent as ShareIcon } from './share.svg'
export { ReactComponent as ShareIcon2 } from './share-1.svg'
export { ReactComponent as SunIcon } from './sun.svg'
export { ReactComponent as VerifyIcon } from './verify.svg'
export { ReactComponent as StatisticsIcon } from './statistics-icon.svg'
export { ReactComponent as ShuffleIcon } from './shuffle.svg'





